version: 2.1
jobs:
  build_and_test:
    parameters:
      v:
        type: string
        default: "8"
    docker:
      - image: circleci/node:<< parameters.v >>
    working_directory: ~/auth0-dbscripts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v<< parameters.v >>-npm-deps-{{ checksum "package-lock.json" }}
            - v<< parameters.v >>-npm-deps-
      - run: npm install
      - save_cache:
          key: v<< parameters.v >>-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Jest tests
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - build_and_test:
          name: build_and_test_node12
          v: "12"
      - build_and_test:
          name: build_and_test_node13
          v: "13"
